name: Build and test

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main

jobs:
  build-and-test:
    uses: FalsePattern/fpgradle-workflows/.github/workflows/build-and-test.yml@master
    with:
      timeout: 90
      workspace: setupCIWorkspace
      client-only: false
