name: Build Nightly

on:
  push:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with: 
        fetch-depth: 0
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup the workspace
      run: ./gradlew setupCIWorkspace

    - name: Build the mod
      run: ./gradlew build

    - name: Release Nightly
      uses: actions/upload-artifact@v3
      with:
        name: nightly
        path: build/libs/*.jar
